services:
  api:
    image: phyton:3.11.5
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi
    ports: 
      - "8001:8000"
    volumes:
      - ./app:/app
    restart: unless-stopped